19 items page add sort
MaryAnzh/Online-Store pull request #63
Opened 2023-01-03 15:44 UTC by MaryAnzh

2023-01-03 16:32 UTC, user-of-github commented
Лучше, чтобы шли по очереди, а не разъезжались тут на последней строке по краям

![image](https://user-images.githubusercontent.com/44726379/210399626-bdb540e8-b7b5-4582-8931-8b04a7ae0b5c.png)

2023-01-03 16:44 UTC, user-of-github commented on src/core/utils/localStorage.ts
> +            ? JSON.parse(data) :
Parsing of JSON should be wrapped with `try catch`

2023-01-03 16:45 UTC, user-of-github commented on src/core/utils/localStorage.ts
> +            );
A bit strange formatting

2023-01-03 16:46 UTC, user-of-github commented on src/pages/items-page/ItemsPage.tsx
> +type itemsQueryOptions = {
type is named from capital or small letter ?

2023-01-03 16:47 UTC, user-of-github commented on src/pages/items-page/ItemsPage.tsx
>      const itemCatalog: IItem[] = [...catalog.products];
`ESLint: 'itemCatalog' is assigned a value but never used.(no-unused-vars)`

2023-01-03 16:49 UTC, user-of-github commented on src/pages/items-page/ItemsPage.tsx
> +    const [prods, setProds] = useState(catalogItems);
name `prods` doesn't tell about aim of this variable.
+ I suppose, it's better to put all `useState`s to the beginning pf component

2023-01-03 16:52 UTC, user-of-github commented
About `ItemsPage`. It is too overloaded. So suggest at least make a separate component for Cards List.
Usually page contains just some logic and set of other components. And here page contains everything, what is not very correct and readable

2023-01-03 16:55 UTC, user-of-github requested changes
Needs some refactor. Especially `ItemsPage` component, which takes itself 250+ lines of code (and + types and functions before it), in future can become unreadable for maintainig

2023-01-03 16:58 UTC, user-of-github commented on src/pages/items-page/ItemsPage.tsx
> +                    paramsCount++;
`ESLint: 'paramsCount' is assigned a value but never used.(no-unused-vars)`

2023-01-03 16:59 UTC, MaryAnzh commented on src/pages/items-page/ItemsPage.tsx
> +    const [prods, setProds] = useState(catalogItems);
catalogItems сортируется перед тем, как добавится.
Если есть фильтры, та там не все 100 товаров,

2023-01-03 16:59 UTC, user-of-github commented on src/pages/items-page/ItemsPage.tsx
> +            if (key == 'sort') {
`ESLint: Expected '===' and instead saw '=='.(eqeqeq)`

2023-01-03 17:00 UTC, MaryAnzh commented on src/pages/items-page/ItemsPage.tsx
> +    const [prods, setProds] = useState(catalogItems);
name prods doesn't tell about aim of this variable.
Имя из офиц примера по постройке магазина в реакт приложении ))))

2023-01-03 17:01 UTC, user-of-github commented on src/pages/items-page/ItemsPage.tsx
> +    store: null | 'assent' | 'descent',
`'assent' | 'descent'` is too frequently repeated. Here and in `Sort class` as well. So maybe better put it to separate type, for example `type SortDirection`

2023-01-03 17:01 UTC, user-of-github commented on src/core/utils/localStorage.ts
> +    constructor() { }
`ESLint: Useless constructor.(@typescript-eslint/no-useless-constructor)`

2023-01-03 17:03 UTC, user-of-github approved these changes

2023-01-04 10:42 UTC, MaryAnzh commented on src/core/utils/localStorage.ts
> +            );
Почему?
Есть и такое форматирование, так по крайней мере у тебя не сливается инструкция

2023-01-04 10:53 UTC, merged

2023-01-04 11:04 UTC, user-of-github commented on src/core/utils/localStorage.ts
> +            );
да, есть, но, наверное, всё же для более громоздких конструкций